### ISSUE TITLE
Build error on Julia 1.0 and Ubuntu 16.04

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaLinearAlgebra/Arpack.jl#33] opened 2018-08-21 10:42 UTC
```
julia> Pkg.add("Arpack")
 Resolving package versions...
 Installed Arpack ───────── v0.2.2
 Installed BinaryProvider ─ v0.4.1
  Updating `~/.julia/environments/v1.1/Project.toml`
  [7d9fca2a] + Arpack v0.2.2
  Updating `~/.julia/environments/v1.1/Manifest.toml`
  [7d9fca2a] + Arpack v0.2.2
  [b99e7846] + BinaryProvider v0.4.1
  Building Arpack → `~/.julia/packages/Arpack/Btbe4/deps/build.log`
┌ Error: Error building `Arpack`:
│ ┌ Warning: Could not extract the platform key of https://github.com/JuliaLinearAlgebra/ArpackBuilder/releases/download/v3.5.0-0.2.20/ArpackBuilder.x86_64-linux-gnu.tar.gz; continuing...
│ └ @ BinaryProvider ~/.julia/packages/BinaryProvider/pWVqZ/src/Prefix.jl:224
│ [ Info: Downloading https://github.com/JuliaLinearAlgebra/ArpackBuilder/releases/download/v3.5.0-0.2.20/ArpackBuilder.x86_64-linux-gnu.tar.gz to /home/adam/.julia/packages/Arpack/Btbe4/deps/usr/downloads/ArpackBuilder.x86_64-linux-gnu.tar.gz...
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/adam/.julia/packages/Arpack/Btbe4/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#134(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/adam/.julia/packages/BinaryProvider/pWVqZ/src/Products.jl:409
│  [3] write_deps_file(::String, ::Array{LibraryProduct,1}) at /home/adam/.julia/packages/BinaryProvider/pWVqZ/src/Products.jl:396
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1038
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:388
│  [9] top-level scope at none:0
│ in expression starting at /home/adam/.julia/packages/Arpack/Btbe4/deps/build.jl:40
[13:30:09] ######################################################################## 100.0%
└ @ Pkg.Operations /home/Adama-docs/Adam/linux/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1068
```

I guess I am missing some system package, but what it could be?

On Ubuntu 18.04 I am able to build the package successfully.

**Comment by andreasnoack** [comment] 2018-08-21 13:35
@staticfloat Do you know what is happening here?

**Comment by staticfloat** [comment] 2018-08-21 15:58
Did you install using the official binaries of Julia, or is this a from-source build?

**Comment by adamryczkowski** [comment] 2018-08-21 16:10
Build from source. 
```
julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.74 (2018-08-20)
 _/ |\__'_|_|_|\__'_|  |  Commit f6c48eb* (1 day old master)
|__/                   |

```

**Comment by staticfloat** [comment] 2018-08-21 16:15
This is a known issue with building from source: https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5

The solutions are: (1) install `gfotran7` and use that to build Julia, (2) use the official binaries.  We're working on a more automatic solution.

**Comment by adamryczkowski** [comment] 2018-08-21 16:30
Are you sure Julia supports gcc-7.x? On another system (HPC) I failed to build Julia with gcc-7.3.0. I had to switch to gcc-6.4.0. First I will first try symlinking gfortran7 with gfortran6, because I built Julia with gcc-6.x and I am afraid to get undefined behavior if I start mixing compilers.

-------

What are exactly the differences between building from source and installing a binary anyway? Docs never state those paths would get me something different.

**Comment by staticfloat** [comment] 2018-08-21 16:37
> What are exactly the differences between building from source and installing a binary anyway?

As stated in https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5, the issue is that between major versions of GCC, the backend ABI of `libgfortran` has changed.  This means that code compiled with `gfortran6` cannot be linked with code compiled with `gfortran7`.

> Are you sure Julia supports gcc-7.x?

Yes I am sure.  The official binaries are built with GCC 7.3.0.

> First I will first try symlinking gfortran7 with gfortran5

The problem is that the code generated by any `gfortran` that is not `gfortran7` is incompatible with the precompiled binaries of `Arpack.jl`.  As I said, we're working on a solution where you can get a precompiled binary from any recent GCC version, but that is taking a little while to build, so in the meantime I suggest either changing your compiler version, or using the prebuilt binaries.

**Comment by adamryczkowski** [comment] 2018-08-21 16:42
No luck with the symlink. The same error. 

But the problem does not manifest itself in Julia 1.0 installed from official binaries.

**Comment by staticfloat** [comment] 2018-08-21 16:46
> No luck with the symlink. The same error.

Yes, this is because even if you symlink the compiler to a different name, it's still the same compiler.  You would need to install the proper compiler version because it's actually the code it is generating, not the name of the compiler, that matters.

> But the problem does not manifest itself in Julia 1.0 installed from official binaries.

Yes, that was option (2) in my message above.  I'm going to close this for now, if you want to do a from-source build of Julia and have Arpack.jl work, you must use GCC 7 for now.

**Closed by staticfloat** 2018-08-21 16:46 UTC

**Comment by rvlobato** [comment] 2018-08-21 18:46
I had the same issue on Arch Linux, I tried to contact the package maintainer to see the possibility to rebuilt the package with gcc7.

**Comment by eli-schwartz** [comment] 2018-08-21 19:30
This is not an Arch Linux bug, so don't do that.

Just build it from source...

Also, precompiled binary **anything** should always ship all its own dependencies rather than make inaccurate assumptions about what environment they are used in.

**Comment by staticfloat** [comment] 2018-08-21 20:03
It’s not that we can’t ship the proper libgfortran, it’s that a from-source Julia build already has a libgfortran linked into it, so even if we did ship the proper libgfortran it would not be used because only one libgfortran can be linked into a process at a time.

**Comment by eli-schwartz** [comment] 2018-08-21 20:21
Would it be possible to statically compile it in precompiled arpack binaries, so that it resolves to inline/versioned symbols?

(By "ship all its own dependencies" I did not mean "defeat the purpose of shared libraries entirely, by providing private copies of something only ever used once". That's not using shared libraries -- that's using the shared library **format** but not actually sharing them, with all the downsides of shared libraries and none of the benefits.)

**Comment by rafaqz** [comment] 2018-08-22 05:37
Interestingly I'm getting this error running 0.7.0 on arch linux, but installed from arch repos.

It's possible they are not using the official binaries, but arch is _meant_ to use upstream packages without changes wherever possible.

**Comment by Moelf** [comment] 2018-09-19 07:59
Some people like to use upstream source code instead of upstream binaries.

**Comment by claudefalbriard** [comment] 2019-06-04 14:07
Still getting the error on a binary distributed version under Ubuntu Linux (conda 1.0.3) unable to build "Arpack" receiveing the following error message. 

Error: Error building `Arpack`: 
`│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/claude/.julia/packages/Arpack/cu5By/deps/usr)") is not satisfied, cannot generate deps.jl!`

I've installed the openblas libraries with command "sudo apt-get install libopenblas-dev"
Any hint how to solve this build for julia linear algebra support?
